export const SOCKET_EVENTS = {
  JOIN_CONVERSATION: "conversation:join",
  UPDATE_CONVERSATION: "conversation:update",
  CONVERSATION_UPDATED: "conversation:updated",
  SEND_MESSAGE: "message:send",
  NEW_MESSAGE: "message:new",
  UPDATE_MESSAGE: "message:update",
  MESSAGE_UPDATED: "message:updated",
  REACT_MESSAGE: "message:react",
  MESSAGE_REACTED: "message:reacted",
  PIN_MESSAGE: "message:pin",
  MESSAGE_PINNED: "message:pinned",
  DELETE_MESSAGE: "message:delete",
  MESSAGE_DELETED: "message:deleted",
  TYPING: "message:typing",
  USER_TYPING: "message:user-typing",
  MARK_READ: "conversation:read",
  CONVERSATION_READ: "conversation:read-receipt",
  PRESENCE_SYNC: "presence:sync",
  PRESENCE_LIST: "presence:list",
  PRESENCE_UPDATE: "presence:update"
} as const;
